config/routes.rb
JmvcCommunity::Application.routes.draw do
  
  resources :posts do
    collection do
      get 'tagged/:tag', :as => :tagged, :action => 'tag'
      get 'in-bucket/:bucket', :action => 'bucket', :as => :in_bucket
      get 'user/:user_id', :action => 'user', :as => :by_user
    end
  end
  
  resources :users
  

  

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  
  match "/articles", :to => 'site#articles', :as => :articles
  
  root :to => "posts#index"
  
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :posts, :dependent => :destroy
  
  before_create :set_as_admin_if_first_user
  
  def self.create_with_omniauth(auth)  
    create! do |user|  
      user.provider = auth["provider"]  
      user.uid = auth["uid"]  
      user.name = auth["user_info"]["name"]  
    end  
  end
  
  def set_as_admin_if_first_user
    self.is_admin = true if User.count == 0
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    authorize! :read, User
    @users = User.order('name').paginate(:per_page => 15, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
    end
  end
  
  def update
    @user = User.find(params[:id])
    authorize! :edit, User
    respond_to do |format|
      is_admin = params[:user].delete(:is_admin)
      if current_user.is_admin? and !is_admin.nil?
        @user.is_admin = is_admin
      end
      
      if @user.update_attributes(params[:user]) 
        format.json { render :json => @user}
      else
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_in_listing.html.haml
.user-in-listing{:data => {'user-id' => user.id}, :class => ((user.is_admin? and current_user.try(:is_admin?)) ? 'is-admin' : "")}
  - if !current_user.nil? and current_user.is_admin?
    .approval
      - if user.is_admin?
        %span This user is an admin
      - else
        %span
      - if !current_user.nil? and current_user.is_admin?
        .action.make-admin= user.is_admin?? "Disable admin status" : "Enable admin status"
      .clear
      
  .post-content
    %h2.post-title= user.name
    .post-url= link_to "Posts by user (#{user.posts.approved.count})", by_user_posts_path(user.id)
    
  .clear

app/views/users/_no_users.html.haml
.no-posts= "There are no registered users."

app/views/users/index.html.haml
- if @users.blank?
  = render :partial => "users/no_users"

- else
  %h1.listing= page_entries_info(@users)
  - @users.each do |u|
    = render :partial => "users/in_listing", :locals => {:user => u}
  = will_paginate @users
  .clear