config/routes.rb
JmvcCommunity::Application.routes.draw do
  
  resources :posts do
    collection do
      get 'tagged/:tag', :as => :tagged, :action => 'tag'
      get 'in-bucket/:bucket', :action => 'bucket', :as => :in_bucket
      get 'user/:user_id', :action => 'user', :as => :by_user
    end
  end
  
  resources :users
  

  

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  
  match "/articles", :to => 'site#articles', :as => :articles
  
  root :to => "posts#index"
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  attr_protected :is_approved
  
  belongs_to :user
  
  has_friendly_id :title, :use_slug => true
  acts_as_taggable
  
  validates_presence_of :title
  validate :presence_of_body_or_url
  validates_presence_of :user
  validates_presence_of :tag_list
  
  before_save :process_body, :add_lead
  before_save :set_is_approved
  
  scope :approved, where(:is_approved => true) 
  
  def title=(html)
    write_attribute(:title, Sanitize.clean(html))
  end
  
  def url=(html)
    write_attribute(:url, Sanitize.clean(html))
  end
  
  def tag_list_with_sanitize=(raw_tags)
    clean_tags = Sanitize.clean(raw_tags)
    self.tag_list_without_sanitize = clean_tags
  end
  
  alias_method_chain :tag_list=, :sanitize
  
  def set_is_approved
    if self.user.is_admin?
      self.is_approved = true
    end
  end
  
  def presence_of_body_or_url
    errors.add_to_base('Please fill the body or the url') if body.blank? && url.blank?
  end
  
  def process_body
    #b = self.body.gsub(/(\s+|\A)(https?:\/\/[\S]+)(\s+|\z)/, ' <\2> ')
    self.processed_body = Sanitize.clean(
                            RDiscount.new(self.body.strip).to_html, 
                            :elements => ['a', 'span', 'img', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'pre', 'code', 'b', 'i', 'strong', 'em', 'ul', 'li', 'ol', 'hr', 'br', 'p'],
                            :attributes => {'a' => ['href', 'title'], 'img' => ['src', 'title']},
                            :protocols => {'a' => {'href' => ['http', 'https', 'mailto']}})
  end
  
  def add_lead
    doc = Nokogiri::HTML(self.processed_body)
    paras = doc.css('p')
    self.lead = paras.first.content unless paras.blank?
  end
  
  def is_editable?
    10.minutes.ago.to_i - self.created_at.to_i < 0
  end
  
end


# == Schema Information
#
# Table name: posts
#
#  id          :integer(4)      not null, primary key
#  title       :string(255)
#  cached_slug :string(255)
#  url         :string(255)
#  post        :text
#  user_id     :integer(4)
#  created_at  :datetime
#  updated_at  :datetime
#  is_self     :boolean(1)
#

app/controllers/posts_controller.rb
class PostsController < CommunityController
  
  skip_before_filter :authenticate_user!
  
  before_filter :authenticate_user!, :except => [:index, :show, :tag, :user, :bucket]
  
  # GET /posts
  # GET /posts.xml
  def index
    authorize! :read, Post
    @posts = Post.accessible_by(current_ability).order('created_at DESC').paginate(:per_page => 15, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
      format.rss { render :layout => false } 
    end
  end

  def bucket
    authorize! :read, Post
    @bucket = Bucket.find_by_slug params[:bucket]
    raise ActiveRecord::RecordNotFound if @bucket.nil?
    @posts = get_posts_from_bucket(@bucket)
    render :action => 'index'
  end
  
  def tag
    authorize! :read, Post
    @bucket = {:name => "Tagged with #{params[:tag]}", :tags => [params[:tag]]}
    @posts = get_posts_from_bucket(@bucket)
    render :action => 'index'
  end
  
  def user
    authorize! :read, Post
    user = User.find params['user_id']
    @posts = user.posts
                 .accessible_by(current_ability)
                 .order('created_at DESC')
                 .paginate(:per_page => 15, :page => params[:page])
    @has_posts = " from #{user.name}"
    @no_posts = " from #{user.name}"
    render :action => 'index'
  end

  # GET /posts/1
  # GET /posts/1.xml
  def show
    
    @post = Post.find(params[:id])
    
    authorize! :read, @post
    
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
      format.json { render :json => @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.xml
  def new
    authorize! :write, Post
    @post = current_user.posts.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    authorize! :edit, @post
  end

  # POST /posts
  # POST /posts.xml
  def create
    authorize! :write, Post
    @post = current_user.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.xml
  def update
    @post = Post.find(params[:id])
    authorize! :edit, Post
    respond_to do |format|
      is_approved = params[:post].delete(:is_approved)
      if current_user.is_admin? and !is_approved.nil?
        @post.is_approved = is_approved
      end
      
      if @post.update_attributes(params[:post]) 
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
        format.json { render :json => @post}
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
        format.json { render :json => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.xml
  def destroy
    @post = Post.find(params[:id])
    authorize! :destroy, @post
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
  
  protected
    def get_posts_from_bucket(bucket)
      @no_posts = "tagged with #{bucket[:tags].to_sentence(:two_words_connector => ' or ', :last_word_connector => ' or ')}"
      @has_posts = " tagged with <b>#{@bucket[:tags].to_sentence(:two_words_connector => ' or ', :last_word_connector => ' or ')}</b>"
      Post.accessible_by(current_ability).tagged_with(bucket[:tags], :any => true).paginate(:per_page => 15, :page => params[:page], :order => 'created_at DESC')
    end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= simple_form_for(@post) do |f|
  - if @post.errors.any?
    #error_explanation
      %h2
        = pluralize(@post.errors.count, "error") 
        prohibited this post from being saved:
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg
  = f.input :title
  = f.input :body
  .preview-post-wrapper
    .preview-post Preview post
    .clear
    .post-body
  = f.input :url
  = f.input :tag_list
  .action
    = f.submit

app/views/posts/_in_listing.html.haml
.post-in-listing{:class => ('post-not-approved' unless post.is_approved?),:data => {:'post-id' => post.cached_slug}}
  - if !current_user.nil? and current_user.is_admin? or (current_user == post.user and !post.is_approved?)
    .approval
      %span= post.is_approved?? "This post is already approved." : "This post is not approved by administration yet."
      - if !current_user.nil? and current_user.is_admin?
        .action.delete Delete
        .action.approve= post.is_approved?? "Disapprove" : "Approve"
        .action.expand Expand
      
  -#image_tag Gravatar.new(post.user.email).image_url(:size => 40), :class => 'gravatar'
  .post-content
    
    %h2.post-title= link_to post.title, post
    - unless post.lead.blank?
      .post-body= post.lead 
    - unless post.url.blank?
      .post-url= link_to post.url, post.url
    .tags= post.tag_list.map{|t| link_to(t, tagged_posts_path(t))}.join('').html_safe
    .posted-by Posted by <b>#{post.user.name}</b> #{time_ago_in_words post.created_at} ago
  .clear

app/views/posts/_no_posts.html.haml
- why = why.nil?? "" : " " + why.strip
.no-posts= "There are no posts#{why}."

app/views/posts/edit.html.haml
%h1.listing Editing post

= render 'form'

app/views/posts/index.html.haml
- if @posts.blank?
  = render :partial => "posts/no_posts", :locals => {:why => @no_posts}

- else
  %h1.listing= "#{page_entries_info(@posts)}#{@has_posts.to_s}".html_safe
  - @posts.each do |p|
    = render :partial => "posts/in_listing", :locals => {:post => p}
  = will_paginate @posts
  .clear

app/views/posts/new.html.haml
%h1.listing New post
= render 'form'

app/views/posts/show.html.haml
.show-post
  .posted-by Posted by <b>#{@post.user.name}</b> #{time_ago_in_words @post.created_at} ago
  - if can? :edit, @post
    = link_to 'Edit post', edit_post_path(@post), :class => 'edit-post'
  %h1= @post.title
  .clear
  .tags= @post.tag_list.map{|t| link_to(t, tagged_posts_path(t))}.join('').html_safe
  .clear
  - unless @post.processed_body.blank?
    - preserve do
      .post-body=@post.processed_body.html_safe
  - unless @post.url.blank?
    .post-body= link_to @post.url, @post.url
    
:erb
  <div id="disqus_thread"></div>
  <script type="text/javascript">
      /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
      var disqus_shortname = 'jmvccommunitypage'; // required: replace example with your forum shortname

      // The following are highly recommended additional parameters. Remove the slashes in front to use.
      var disqus_identifier = 'post-<%= @post.id %>';
      var disqus_url = 'http://community.javascriptmvc.com/posts/<%= @post.cached_slug %>';

      /* * * DON'T EDIT BELOW THIS LINE * * */
      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>
  
  