config/routes.rb
JmvcCommunity::Application.routes.draw do
  
  resources :posts do
    collection do
      get 'tagged/:tag', :as => :tagged, :action => 'tag'
      get 'in-bucket/:bucket', :action => 'bucket', :as => :in_bucket
      get 'user/:user_id', :action => 'user', :as => :by_user
    end
  end
  
  resources :users
  

  

  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

  
  match "/articles", :to => 'site#articles', :as => :articles
  
  root :to => "posts#index"
  
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title JavaScriptMVC Community
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <link rel="alternate" type="application/rss+xml" href="/posts.rss" title="RSS Feed">
    = stylesheet_link_tag 'reset', '960', 'text', 'museoslab', '/javascripts/highlight/styles/sunburst', 'community'
    = csrf_meta_tag
  %body
    #wrapper
      .container_16
        %header
          = link_to image_tag('community/logo.png', :id => 'logo'), "/"
          .right-header
            .logout-and-edit-info
              - if current_user
                Welcome, #{current_user.name} - 
                = link_to "Sign Out", signout_path
              - else
                .sign-in-button Sign in to post
                .sign-in-popup
                  Sign in with one of the following providers:
                  .sign-in-providers
                    = link_to image_tag('community/icons/twitter.png'), '/auth/twitter'
                    = link_to image_tag('community/icons/facebook.png'), '/auth/facebook'
                    = link_to image_tag('community/icons/google.png'), '/auth/open_id?openid_url=https://www.google.com/accounts/o8/id'
              
            %nav
              %ul
                %li= link_to 'All posts', posts_path
                - Bucket.all.each do |b|
                  %li= link_to b[:name], in_bucket_posts_path(b[:slug])
                - if can? :write, Post
                  %li#new-post= link_to 'New Post', new_post_path, :id => 'new-post'
                - if current_user.try(:is_admin?)
                  %li= link_to 'Users', users_path
          
          .clear
        #content
          .left
            - unless notice.blank?
              %p.notice= notice
            - unless alert.blank?
              %p.alert= alert
            =yield
          .right
            = render_cell :latest_posts, :display
            = render_cell :tag_cloud, :display
            .sidebar-box
              %h1 Tweets on JavaScriptMVC
              #twitter-feed
          .clear
        %footer
          <a href="http://javascriptmvc.com">JavaScriptMVC</a> is brought to you by <a href="http://jupiterit.com">Jupiter</a>
    = javascript_include_tag "jquerymx-1.0.custom/jquery-1.4.3", "jquerymx-1.0.custom/jquerymx-1.0.custom", "showdown", 'highlight/highlight', 'highlight/languages/javascript', "application"
    :erb
      <script type="text/javascript">
      		var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
      		document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
      </script>
      <script type="text/javascript">
      		try{
      		var pageTracker = _gat._getTracker("UA-2302003-4");
      		pageTracker._trackPageview();
      		} catch(err) {}
      </script>